### DISCUSSION TITLE
GDB client does not support HW or SW breakpoints

### DISCUSSION THREAD

**Discussion by JackNWhite** [bloombloombloom/Bloom#119] [Q&A] [answered]
Hello folks,

I have an ATmegaS64M1 to which I am connecting via debugWire with a PICkit4.

**bloom**   1.0.0
**avr-gdb** (AVR_8_bit_GNU_Toolchain_3.7.0_1796) 7.8

I am able to run bloom and have it connect to the chip:

```
[MT]: [INFO] Selected environment: "default"
[TC]: [INFO] Starting TargetController
[TC]: [INFO] Connecting to debug tool
[TC]: [INFO] Debug tool connected
[TC]: [INFO] Debug tool name: MPLAB PICkit 4
[TC]: [INFO] Debug tool serial:
[TC]: [INFO] Activating target
[TC]: [INFO] Target activated
[TC]: [INFO] Target ID: 0x1e9684
[TC]: [INFO] Target name: ATmega64M1
[TC]: [INFO] Available hardware breakpoints: 0
[DS]: [INFO] Starting DebugServer
[DS]: [INFO] Selected DebugServer: AVR GDB Remote Serial Protocol Debug Server
[DS]: [INFO] GDB RSP address: 127.0.0.1
[DS]: [INFO] GDB RSP port: 1442
[DS]: [INFO] DebugServer ready
[DS]: [INFO] Waiting for GDB RSP connection
```

I try to connect this way:
```
avr-gdb myBinary.elf
(gdb) target remote :1442
Remote debugging using :1442
Remote connection closed
```

Immediately, in the bloom log, I get this:
```
[DS]: [INFO] Accepted GDP RSP connection from 127.0.0.1
[DS]: [INFO] Handling QuerySupport packet
[DS]: [ERROR] Invalid GDB RSP client - GDB client does not support HW or SW breakpoints - closing connection
[DS]: [INFO] Waiting for GDB RSP connection
[MT]: [INFO] Shutting down Bloom
[DS]: [INFO] Shutting down DebugServer
[TC]: [INFO] Shutting down TargetController
[TC]: [INFO] Deactivating target
[TC]: [INFO] Closing debug tool
[SH]: [INFO] Shutting down SignalHandler
```

My bloom config is:
```yaml
environments:
  default:
    shutdownPostDebugSession: true

    tool:
      name: "pickit-4"

    target:
      name: "atmega64m1"
      physicalInterface: "debug-wire"
      # hardwareBreakpoints: true
      manageDwenFuseBit: true

    server:
      name: "avr-gdb-rsp"
      ipAddress: "127.0.0.1"
      port: 1442
      rangeStepping: true

insight:
  activateOnStartup: false
```

Has anyone had this problem? Have you fixed it?
