### DISCUSSION TITLE
Migrating an old bloom.yaml configuration file to v2.0.0+

### DISCUSSION THREAD

**Discussion by navnavnav** [bloombloombloom/Bloom#123] [General]
v2.0.0 contains some breaking changes to Bloom's project configuration file (bloom.yaml).
When upgrading to v2.0.0+, some small amendments will need to be made to any bloom.yaml file that was used with the older versions. This tutorial will take you through the changes.

### camelCase keys and dash-case values, to snake_case
Bloom's project configuration file used to use camelCase for keys, and dash-case for values, but has since been changed to use snake_casing for both:

Old:
```yaml
environments:
  default:
    shutdownPostDebugSession: true

    tool:
      name: "curiosity-nano"

    target:
      name: "avr64ea48"
      physicalInterface: "updi"
      hardwareBreakpoints: true

    server:
      name: "avr-gdb-rsp"
      ipAddress: "127.0.0.1"
      port: 1442
      rangeStepping: true

insight:
  activateOnStartup: false
```

New:

```yaml
environments:
  default:
    shutdown_post_debug_session: true

    tool:
      name: "curiosity_nano"

    target:
      name: "avr64ea48"
      physical_interface: "updi" 
      hardware_breakpoints: true

    server:
      name: "avr_gdb_rsp"
      ip_address: "127.0.0.1"
      port: 1442
      range_stepping: true

insight:
  activate_on_startup: false
```

Bloom will no longer recognize camelCase keys and dash-case values. All keys and values must be renamed to their corresponding snake_case version.

### `variantName` has been removed

The `variantName` target config param has been removed in this release. Remove it from your bloom.yaml.

---

To make things easier, you could run the following command to make most of the required adjustments to the bloom.yaml, in your current working dir. But beware: It will apply case conversion across the entire file. So if you have any comments in the file, it may screw them up.

```bash
cp ./bloom.yaml ./bloom.old.yaml; echo -e "$(cat ./bloom.yaml | sed 's/[A-Z]/_\l&/g' | sed 's/-/_/g' | sed 's/debug_logging_enabled/debug_logging/g')" > ./bloom.yaml
```
That's it! You should now be good to run Bloom v2.0.0
