### DISCUSSION TITLE
[TUTORIAL] Migrating an old bloom.yaml configuration file to v1.0.0+

### DISCUSSION THREAD

**Discussion by navnavnav** [bloombloombloom/Bloom#89] [General]
### Migrating an old bloom.yaml configuration file to v1.0.0+

If you''ve just upgraded Bloom from a version prior to 1.0.0, to 1.0.0 or later, you will need to make some small amendments to any bloom.yaml file that was used with the older versions. This tutorial will take you through the changes.

#### Rename the `debugTool` key to `tool`

The `debugTool` key was renamed to `tool` in the major release.

Old:

```yaml
environments:
  someEnvironmentName:
    debugTool:
      # ...
```

New:

```yaml
environments:
  someEnvironmentName:
    tool:
      # ...
```

#### Rename the `debugServer` key to `server`

The `debugServer` key was renamed to `server` in the major release.

Old:

```yaml
environments:
  someEnvironmentName:
    debugServer:
      # ...
```

New:

```yaml
environments:
  someEnvironmentName:
    server:
      # ...
```

#### Replace the generic `avr8` target configuration value

The generic `avr8` target name allowed users to take advantage of Bloom's ability to identify the target via the target signature. But this didn't always work, and it resulted in a lot of complexity in the code base. As a result, it was stripped from Bloom in this major version release. See https://github.com/bloombloombloom/Bloom/issues/72 for more.

If you're currently using the `avr8` target name, you must replace it with the specific configuration value for the target. You can find all target configuration values on the [Supported Targets](https://bloom.oscillate.io/docs/supported-targets) page.

Old:

```yaml
environments:
  someEnvironmentName:
    target:
      name: "avr8"
      # ...
```

New:

```yaml
environments:
  someEnvironmentName:
    target:
      name: "avr64dd32" # This is just an example - use the correct configuration value for your target.
      # ...
```

#### Remove the `enabled` Insight config parameter

Before this major release, the Insight GUI would immediately appear at startup, and closing the main Insight window would trigger a shutdown. The `enabled` flag allowed users to disable the Insight GUI, but once disabled, there was no way of enabling it during a debug session. This would mean users would have to terminate their current debug session, update the `enabled` value, then start another debug session. This was a source of frustration.

In this major release, Bloom's default behaviour has changed in the following ways: 

- The Insight GUI will no longer appear immediately at startup. It is effectively disabled by default.
- The Insight GUI can be activated, at any time during a debug session, via the new `monitor insight` (or `mon insight`) GDB command.
- Closing the main Insight window will no longer cause Bloom to shutdown.

With these changes, there was no longer a need for the `enabled` Insight parameter, so it has been removed in this major release.

Old:

```yaml
environments:
  someEnvironmentName:
    insight:
      enabled: true
      # ...
```

New:

```yaml
environments:
  someEnvironmentName:
    insight:
      # ...
```

And given that the `enabled` parameter was the only mandatory Insight parameter, you can now omit the `insight` node, entirely:

```yaml
environments:
  someEnvironmentName:
    # ...
```

If, however, you wish to keep the old behaviour, you can do so with the new `activateOnStartup` and `shutdownOnClose` Insight parameters:

```yaml
environments:
  someEnvironmentName:
    insight:
      activateOnStartup: true # <- If true, the Insight GUI will be appear immediately after startup.
      shutdownOnClose: true # <- If true, Bloom will shutdown when the main Insight window is closed.
```

---

That's it. You should now be able to run Bloom v1.0.0+ with your amended project configuration file.

Alternatively, if you want to be lazy, you could just delete the file and have Bloom recreate it with the `init` CLI command:

```
cd [PATH_TO_PROJECT_ROOT];
rm -f ./bloom.yaml;
bloom init;
```
Then make the appropriate changes for your debug environment.
