### ISSUE TITLE
Issues when stepping into a static library

### ISSUE THREAD

**Issue by sven-hoek** [bloombloombloom/Bloom#110]
Not sure if stepping into the static library is the issue but it seems to happen whenever I try to step into or break in a statically-linked library function.

- Bloom version: 1.0.0 (.deb, installed on Ubuntu 22.04)
- Both library and firmware were built with `-Og`.
- Debugging an ATmega328PB via DebugWire through an Atmel-ICE
- Error message when trying to step into the function:
  ```
  [ERROR] Failed to decode AVR8 opcode at byte address 0x000001be - the instruction will have to be intercepted. Please enable debug logging, reproduce this message and report as an issue via https://bloom.oscillate.io/report-issue
  ```
- Error message from avr-gdb:
  ```
  Breakpoint 1, main () at .././main.c:82
  82	    CH9120Initialisation();  // initialize the CH9120 Serial to Ethernet controller
  ../../src/gdb/gdbtypes.c:931: internal-error: type* create_range_type(type*, type*, const dynamic_prop*, const dynamic_prop*, LONGEST): Assertion `TYPE_LENGTH (index_type) > 0' failed.
  A problem internal to GDB has been detected,
  further debugging may prove unreliable.
  ```

When debugging within VSCode, the Debugging stops but when I run `avr-gdb` in the terminal and connect to Bloom's gdb-server, I can continue, though never able to step into a library function.
Bloom itself doesn't always crash and so far I couldn't really pin down when it does. It happens when I am a few lines above a library function call and then try to _step over_ (but not even the library function call itself)...I'll also report the bug on the avr-gdb side.

If there's anything else I could try or any info I could provide, let me know.

**Comment by navnavnav** [comment]
Hey @sven-hoek 

Thanks for reporting this.

When range stepping is enabled, Bloom attempts to analyze all instructions within the given range, and intercept those that may take the target outside of the range. The error message suggests that Bloom was unable to decode a particular opcode, and so it was forced to intercept that instruction, as we don't know what it will do. However, that error is not considered to be fatal and should not result in Bloom crashing or shutting down abruptly.

A few things I need from you, please:

- What version of GDB are you currently using?
- Could you enable debug logging, reproduce that error, and then send me the full debug log? To enable debug logging, set the `debugLogging` param to `true` in the root node of your bloom.yaml:

  ```yaml
  debugLogging: true

  environments:
  ...
- Can you provide a dump of program memory, around the address at which Bloom failed to decode the opcode (`0x000001BE`)? You can obtain this via GDB, using `x/10b 0x000001BB` - that should output 10 bytes of program memory, starting at `0x000001BB`.
- In addition to a program memory dump, it will help to know if GDB has similar issues decoding that opcode. Could you try running `x/10bfi 0x000001BB` in GDB? It will attempt to decode the opcodes around that address and output them.

As for the fatal error in GDB, I'm not sure if that's even related to the range step, as Bloom simply intercepts any instructions that it could not decode, So it shouldn't affect GDB at all. Have you tried disabling range stepping? Does GDB still crash? You can disable range stepping by setting `rangeStepping` to `false` in your server config, in bloom.yaml:

```yaml
server:
  rangeStepping: false
```

If the issue in GDB is related to range stepping, you can just leave range stepping disabled, for the time being. It will result in degraded stepping performance but at least it won't crash.
